### ISSUE TITLE
MSBuild Error MSB8020

### ISSUE THREAD

**Issue by alexa872** [glmcdona/Process-Dump#22]
i wanted to compile it from source code but this error is preventing me, so i tried to copy & paste the files into a new empty project but i got about 60 errors (just 2 but there were many of them)::: 
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2664?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2664)%26rd%3Dtrue&view=msvc-160

&&

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2440)%26rd%3Dtrue&view=msvc-160

but if you are considering upgrading your project to vs 2019, i think this is the solution:::
https://docs.microsoft.com/en-us/cpp/dotnet/how-to-convert-system-string-to-wchar-t-star-or-char-star?view=msvc-160

anyways ill download the compiled release

**Comment by glmcdona** [comment]
Fixed with this change to upgrade it to the latest toolset:
https://github.com/glmcdona/Process-Dump/pull/23/commits/6c46df2eff263b461653ece7dcf6ffdef824f7e1

Compiles in latest VS2019 now.

**Comment by alexa872** [comment]
> Fixed with this change to upgrade it to the latest toolset:
> [6c46df2](https://github.com/glmcdona/Process-Dump/commit/6c46df2eff263b461653ece7dcf6ffdef824f7e1)
> 
> Compiles in latest VS2019 now.

thank you man i appreciate it
